### ISSUE TITLE
train&cv

### ISSUE THREAD

**Issue by neverneverendup** [billy-inn/NFETC#1]
Dear Author:
I read your paper recently.NFETC is a good model in FETC.
​
I want to implement your code ,but I have two questions.
1.Will the train end automatically?I use GTX1080TI to train your model , after 2 days , it is still running..How long will it cost ...?
2.Here is a funtion .I don't know what does "cv" mean.Could you tell me...And I'm a "freshman" in FETC domain.Please tell me the meaning of pacc &eacc  also.I remember there is only strict acc in your paper..
  
![image](https://user-images.githubusercontent.com/41896224/43387310-b1ce3568-9418-11e8-95fa-fbd23b04c7e2.png)

Thanks!

**Comment by billy-inn** [comment]
1. For the default setting, you choose to tune the parameters which will run the experiments for many times. You can check the log for what's going on. See the arguments for task.py for more details. The easiest way is set `-e 1` to make it just run one time.
2. cv should be validation to be more accurate, it just runs the same experiment with multiple runs. eacc is equivalent to strict accuracy. For pacc, you can check the code for details.

**Comment by deepaknlp** [comment]
pacc: Partial accuracy (if any of the label or sublabel predicted by the system, it makes count here)
eacc: Exact accuracy
