### ISSUE TITLE
T-SNE visualization of type embeddings

### ISSUE THREAD

**Issue by zhaoluffy** [billy-inn/NFETC#4]
Hi,
parameter 'output/W' is your type embeddings?  And I am trying visualization it, but cann't get expected results in your paper reported.  

I using TSNE in sklearn.manifold and the core code is ：
"tsne = TSNE()
W = tsne.fit_transform(W)
“
Can you share your idea about my problem. Thanks

**Comment by billy-inn** [comment]
First question, yes.
Second question, I use R to plot the TSNE visualization. 

A nice blog to explain TSNE: https://distill.pub/2016/misread-tsne/. Basically, it's hard to reproduce exactly the same TSNE visualization due to inherent randomness of both the neural model and the TSNE algorithms.

**Comment by zhaoluffy** [comment]
It's helpful for me , Thanks
