### ISSUE TITLE
i‘m not understand some experiment setting

### ISSUE THREAD

**Issue by herbertchen1** [billy-inn/NFETC#5]
the task.cv is actually not using different data split, it uses different random init model param？
I didn't find the use of cross validation data, there is some test data in the task.refit() process. Is it necessary?
The code  use the training data (no ground truth) to fine tune the hyper parameter , then use the hyper parameter to training a model ,get the result over the test data ??

How could it works ? 
Amazing!!

**Comment by billy-inn** [comment]
It should be 'validation' instead of 'cv' for the function name. I use 10% of the testing data as the development data to tune the parameters and evaluate on the rest, as described in the paper. I only use the 'refit' function for debugging.

**Comment by herbertchen1** [comment]
thanks ， it’s really a nice work！

**Comment by herbertchen1** [comment]
hey，the wikim is the modified type tree? via the original type tree , it seems only can get 55+ eacc, while the improved tree got 69.9% in my machine? Am I in right situation??
